# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'

target 'TDOS_DiagnoseDemo' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!

  # Pods for TDOS_DiagnoseDemo
  pod 'TDOS_Diagnose', :path => '../', :modular_headers => true


end
